name: Keep Alive

on:
  schedule:
    - cron: 0 * * * *

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Keep Alive
        run: |
          curl -s -o /dev/null https://studious-space-tribble-x59g7qvx4jpqcvvwp.github.dev
